.TH SNS 1
.SH NAME
sns \- Flexible object file splicing and editing.
.SH SYNOPSIS
.B sns

.SH DESCRIPTION
.B sns
is an application that encourages gross abuse of the ELF file format by allowing one to do whatever one sees fit with the file within the limits of the standard and beyond.


.SH OPTIONS
